# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bec0cf4fbb3f63a60e584de2340c5fb59e41e132748ce00ccbc15239bd9e205020ea93bcd830ff3f1f3909b686c05bbdf1bab03bfb4d5cda8f07b1b3019a0b1

test:
  secret_key_base: 4df37c493c242df4ea0f1b1cdc8cf00e6a13e11335ac2fea038c6f0b6605a5019ad87edadb727db29272e6fc2a3ebf2f02876e8a17eb4d39830b83ad58f92b41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
